=== pamory19/socialnetwork/src/main/java/com.solvd.socialnetwork/xml/PostXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Posts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Post" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="caption" type="xs:string"/>
                            <xs:element name="accountId" type="xs:Long"/>
                            <xs:element name="creationDate" type="xs:date"/>
                            <xs:element name="Shares">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Share" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="shareCount" type="xs:Long"/>
                                                    <xs:element name="accountId" type="xs:Long"/>
                                                    <xs:element name="postId" type="xs:Long"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Comments">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Comment" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="text" type="xs:string"/>
                                                    <xs:element name="accountId" type="xs:Long"/>
                                                    <xs:element name="postId" type="xs:Long"/>
                                                    <xs:element name="creationDate" type="xs:date"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Views">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="View" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="viewCount" type="xs:Long"/>
                                                    <xs:element name="accountId" type="xs:Long"/>
                                                    <xs:element name="postId" type="xs:Long"/>
                                                    <xs:element name="profileId" type="xs:Long"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Reactions">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Reaction" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="reactionType" type="xs:string"/>
                                                    <xs:element name="accountId" type="xs:Long"/>
                                                    <xs:element name="postId" type="xs:Long"/>
                                                    <xs:element name="profileId" type="xs:Long"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
   </xs:element>
</xs:schema>

=== pamory19/socialnetwork/src/main/java/com.solvd.socialnetwork/xml/PostXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<Posts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation='PostXSD.xsd'>
    <Post id="1">
        <caption>Just chilling</caption>
        <accountId>2</accountId>
        <creationDate>2023-01-05T13:00:34</creationDate>
        <Shares>
            <Share id="1">
                <shareCount>4</shareCount>
                <accountId>2</accountId>
                <postId>1</postId>
            </Share>
            <Share id="2">
                <shareCount>13</shareCount>
                <accountId>1</accountId>
                <postId>1</postId>
            </Share>
        </Shares>
        <Comments>
            <Comment id="1">
                <accountId>1</accountId>
                <postId>1</postId>
                <text>You look great!</text>
                <creationDate>2023-01-12</creationDate>
            </Comment>
        </Comments>
        <Views>
            <View id="1">
                <accountId>1</accountId>
                <viewCount>10</viewCount>
                <postId>1</postId>
                <profileId>1</profileId>
            </View>
        </Views>
        <Reactions>
            <Reaction id="1">
                <accountId>1</accountId>
                <reactionType>Like</reactionType>
                <postId>1</postId>
                <profileId>1</profileId>
            </Reaction>
        </Reactions>
    </Post>
</Posts>
